---
title:            LinuxTurtle's Lair
description:      Musings and snappings from the LinuxTurtle

# put your disqus here
disqus_shortname: 
reading_time:     true # if true, shows the estimated reading time for a post
words_per_minute: 200
logo:             images/logo.png # logo visible in the topbar
excerpt_separator: <!--more-->
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000

url: http://blog.linuxturtle.net

# draw your top menu here
# each item must have a title and a url.
#   To list post categories. use type: 'categories'
#   To create sub categories. add a submenu item
# See the example
menu:
  - title: 'Home'
    url: '/'
  - title: 'Tags'
    url: '/tags'
  - title: 'Posts'
    url: '/posts'
    type: 'posts'
#  - title: 'Favorites'
#    url: '#'
  - title: 'About'
    url: '/about'
  - title: 'RSS'
    url: '/feed.xml'

# Owner/author information
owner:
  name:           Brett Johnson (linuxturtle)
  site:           http://blog.linuxturtle.net
  avatar:         images/avatar.jpg
  bio:            "I like turtles. I also like Linux. You might say I'm a geek :)"
  email:          brett@linuxturtle.net
  twitter: linuxturtle # if no twitter in this config, the twitter follow button will be removed
  github: linuxturtle

# Twitter account associated with the site if different from owner/author twitter account.
# Used in Twitter cards.
twitter:

# Social networking links used in author block underneath posts. Update and remove as you like.
social:
  - title: "github"
    url: "https://github.com/linuxturtle"
  - title: "linkedin"
    url: "https://br.linkedin.com/in/linuxturtle"
#  - title: "youtube"
#    url: "https://www.youtube.com/channel/UCfnSek-9HPWOx5e2pH7VFgg"

# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Denver
locale:      en_US
future:      true
highlighter: rouge
markdown:    kramdown
sass:
  sass_dir: _sass
  style: compressed

# https://jekyllrb.com/docs/permalinks/
permalink:  pretty

# Amount of post to show on home page
paginate: 5

# if true, shows the floatting share buttons
float_share: true

# Octopress
# Default extensions
post_ext: md
page_ext: md
# Found in _templates/
post_layout: post
page_layout: page
# Format titles with titlecase?
titlecase: true

include: [".htaccess"]
exclude:
- demo/*
- config
- Gemfile
- Gemfile.lock
- README.md
- LICENSE/*
- log
- tmp
- less
- test
- spec
- Gruntfile.js
- package.json
- node_modules

plugins:
- jekyll-avatar
- jekyll-feed
- jekyll-paginate
- jekyll-seo-tag
- jekyll-gist

theme: neo-hpstr-jekyll-theme
